name: Auto Release

on:
  push:
    tags:
      - 'v*.*.*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 打包为压缩文件
      - name: Create Archive
        run: |
          mkdir -p release
          chmod +w release
          ls
          echo "下一条"
          ls ./LumiVerseFramework/
          zip -r release/LumiverseFramework-${GITHUB_REF##*/}.zip ./LumiVerseFramework/
      # 上传
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: release/LumiverseFramework-${GITHUB_REF##*/}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
